version: '3'
services:
  trip-schedule-db:
    container_name: trip-schedule-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB= ${DB_NAME}